# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 901b678edad4a4d20f7cea4597e94623d481884abfe5808ff71be92dba4a079cac839d838de5b15b5e2ed61b1308b45396ebafcb69d036c346f1e606c9deec29

test:
  secret_key_base: 1811166aa1e47df0af6e5f9bd98e25e7b2833332508c524a31138bfbbd3211ad36f6095ee2feba71f54dbc223441b32785cb9c5e197c47f64d9c80f3df739986

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
